name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...

  build-image:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
